name: Deploy to Minikube using GitHub Actions

on:
  - push
  # push:
  #   branches:
  #     - main

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
      - uses: actions/checkout@v4
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: minikube kubectl -- get po -A
        # run: kubectl get pods -A
      - name: Build image
        run: |
# minikube image build -t devopshint/node-app:latest .
            export SHELL=/bin/bash
            eval $(minikube -p minikube docker-env)
            docker build -f ./Dockerfile -t devopshint/node-app:latest .
            echo -n "verifying images:"
            docker images         
      - name: Deploy to minikube
        run:
          kubectl apply -f k8s-node-app.yaml
      - name: Test service URLs
        run: |
            minikube service list
            minikube service nodejs-app --url
            echo -n "------------------opening the service------------------"
            curl $(minikube service nodejs-app --url)/version

